

# Use root/example as user/password credentials
# command： docker-compose up
version: '3.1'

services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3090:3306"
    volumes:
      - /data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  nestjs-app:
    build: ./backend/nodejs/dist
    ports:
      - "3008:3008"
    environment:
      NODE_ENV: production

  # redis:
  #   image: redis:latest
  #   container_name: myredis
  #   ports:
  #     - "6379:6379"
  #   # 如果需要设置密码，可以使用下面的 command 选项：
  #   command: redis-server --requirepass 123456

  # java_app:
  #   build:
  #     context: ./backend
  #   environment:
  #     - SERVICE_HOST=${SERVICE_HOST}
  #   ports:
  #     - "8081:8888"
  #   volumes:
  #     - /home/ec2-user/app/images:/app/images
  #   depends_on:
  #     - db
  #     - redis

  ssr:
    build:
      context: ./ssr
    ports:
      - "8989:3000"

  # nginx:
  #   build:
  #     context: ./frontend/build
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./frontend/build:/usr/share/nginx/html
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - /home/ec2-user/app/images:/nginx/images

