

version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3090:3306"
    volumes:
      - /data/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

  nestjs-app:
    build: ./backend/nodejs/nest-blog
    ports:
      - "3008:3008"
    environment:
      NODE_ENV: production
    networks:
      - app-network

  # redis:
  #   image: redis:latest
  #   container_name: myredis
  #   ports:
  #     - "6379:6379"
  #   # 如果需要设置密码，可以使用下面的 command 选项：
  #   command: redis-server --requirepass 123456

  # java_app:
  #   build:
  #     context: ./backend
  #   environment:
  #     - SERVICE_HOST=${SERVICE_HOST}
  #   ports:
  #     - "8081:8888"
  #   volumes:
  #     - /home/ec2-user/app/images:/app/images
  #   depends_on:
  #     - db
  #     - redis

  ssr:
    build:
      context: ./ssr/standalone
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    # 设置nginx写入权限
    command: /bin/sh -c "mkdir -p /app/logs && chmod -R 755 /app/logs && nginx -g 'daemon off;'"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssr/standalone/.next/static:/app/ssr/standalone/.next/static
      - ./ssr/standalone/public:/app/ssr/standalone/public
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
